# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Checksum
email: checksum@zigzag.pub
description: >
    A minimal effort blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://checksum.zigzag.pub" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  keyboardscience

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
